main = "src/main.ts"
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2023-11-12"

[env.prod]
name = "blog-bff"
vars = { IS_PROD = "true" }

[env.dev]
name = "blog-bff-dev"
vars = { IS_PROD = "false" }