main = "src/main.ts"
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2024-05-03"
logpush = true

[env.prod]
name = "blog-bff"
vars = { IS_PROD = "true" }

[[env.prod.kv_namespaces]]
binding = "CACHE_KV"
id = "<kv_prod_namespace_id>"

[env.dev]
name = "blog-bff-dev"
vars = { IS_PROD = "false" }

[[env.dev.kv_namespaces]]
binding = "CACHE_KV"
id = "<kv_dev_namespace_id>"
